// Offline tests: node --test tests/
// Live tests (replay through RenderDoc) run only when RDGPU_TEST_CAPTURE points at a .rdc
// and RenderDoc is discoverable (RDGPU_RENDERDOC or RENDERDOC_PYTHON_PATH).
import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import test from 'node:test';
import zlib from 'node:zlib';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const SKILL = path.join(ROOT, '.agents', 'skills', 'renderdoc-gpu');
const CLI = path.join(SKILL, 'scripts', 'rdgpu.mjs');
const PROJECT = path.join(ROOT, 'dev', 'fixtures', 'MiniUnityProject');

const tmp = () => fs.mkdtempSync(path.join(os.tmpdir(), 'rdgpu-test-'));
function cli(args, opts = {}) {
  const r = spawnSync(process.execPath, [CLI, ...args], { encoding: 'utf8', env: { ...process.env, ...opts.env }, timeout: opts.timeout || 60000 });
  return { code: r.status, out: r.stdout, err: r.stderr };
}

const { Case, counterKind } = await import(path.join(SKILL, 'scripts', 'lib', 'case.mjs'));
const { expandCounterSpec } = await import(path.join(SKILL, 'scripts', 'lib', 'presets.mjs'));
const { shaderStats } = await import(path.join(SKILL, 'scripts', 'lib', 'shaderstats.mjs'));
const { setupNvPerf } = await import(path.join(SKILL, 'scripts', 'lib', 'setup.mjs'));

// ---------------------------------------------------------------- synthetic case

function writeCase(dir, { actions, counters, state = [], shaders = [], info = {}, files = {} }) {
  fs.mkdirSync(path.join(dir, 'shaders'), { recursive: true });
  fs.writeFileSync(path.join(dir, 'case.json'), JSON.stringify({ version: 1, capture: path.join(dir, 'x.rdc'), host: 'test', options: {} }));
  fs.writeFileSync(path.join(dir, 'info.json'), JSON.stringify({ api: 'D3D11', vendor: 'nVidia', counters: [
    { id: 1, name: 'GPU Duration', unit: 'Seconds', family: 'generic' },
    { id: 12, name: 'PS Invocations', unit: 'Absolute', family: 'generic' },
    { id: 2, name: 'Input Vertices Read', unit: 'Absolute', family: 'generic' },
    { id: 3000001, name: 'l1tex__t_sector_hit_rate.avg.pct', unit: 'Percentage', family: 'nvidia', description: 'hit <br/>rate' },
  ], textures: [], ...info }));
  fs.writeFileSync(path.join(dir, 'actions.jsonl'), actions.map((a) => JSON.stringify(a)).join('\n') + '\n');
  fs.writeFileSync(path.join(dir, 'state.jsonl'), state.map((a) => JSON.stringify(a)).join('\n') + '\n');
  fs.writeFileSync(path.join(dir, 'shaders.json'), JSON.stringify(shaders));
  fs.writeFileSync(path.join(dir, 'counters-generic.json'), JSON.stringify(counters));
  for (const [f, text] of Object.entries(files)) fs.writeFileSync(path.join(dir, 'shaders', f), text);
}

const DXBC = `// Generated by Microsoft (R) HLSL Shader Compiler
ps_5_0
dcl_temps 7
sample_indexable(texture2d)(float,float,float,float) r0.xyzw, v1.xyxx, t0.xyzw, s0
loop
  sample_l_indexable(texture2d)(float,float,float,float) r1.xyzw, r2.xyxx, t1.xyzw, s0, l(0)
  add r0.xyz, r0.xyzx, r1.xyzx
endloop
mov o0.xyzw, r0.xyzw
ret
// Approximately 42 instruction slots used`;

function frame(dir, { psScale = 1, lights = 4, hash = 'a' } = {}) {
  const actions = [
    { eid: 1, parent: 0, depth: 0, name: 'Camera.Render', kind: 'marker', children: 3 },
    { eid: 2, parent: 1, depth: 1, name: 'Opaque', kind: 'marker', children: 2 },
    { eid: 3, parent: 2, depth: 2, name: 'DrawIndexed(36)', kind: 'draw', indices: 36, instances: 1, children: 0 },
    { eid: 4, parent: 2, depth: 2, name: 'DrawIndexed(9000)', kind: 'draw', indices: 9000, instances: 1, children: 0 },
    { eid: 5, parent: 1, depth: 1, name: 'Bloom', kind: 'marker', children: 1 },
    { eid: 6, parent: 5, depth: 2, name: 'Draw(3)', kind: 'draw', indices: 3, instances: 1, children: 0 },
    { eid: 7, parent: 1, depth: 1, name: 'Clear', kind: 'clear', children: 0 },
  ];
  const counters = { label: 'generic', counters: ['GPU Duration', 'PS Invocations', 'Input Vertices Read', 'l1tex__t_sector_hit_rate.avg.pct'],
    units: ['Seconds', 'Absolute', 'Absolute', 'Percentage'], missing: [], repeat: 1, data: [
      [3, 0.0001, 1000, 36, 90], [4, 0.0009 * lights / 4, 9000, 9000, 80], [6, 0.002 * psScale, 921600 * psScale, 3, 50], [7, 0.0001, 0, 0, null]] };
  const state = [
    { eid: 3, shaders: { vs: 10, ps: 11 }, viewport: [0, 0, 1280, 720] },
    { eid: 4, shaders: { vs: 10, ps: 11 }, viewport: [0, 0, 1280, 720] },
    { eid: 6, shaders: { vs: 12, ps: 13 }, viewport: [0, 0, 1280 * Math.sqrt(psScale), 720 * Math.sqrt(psScale)] },
  ];
  const shaders = [
    { id: 11, key: '11', stage: 'ps', name: 'Shader 11', entry: 'frag', encoding: 'DXBC', flags: [['@cmdline', '/Zi /Od']], files: [],
      cbuffers: [{ name: 'UnityPerMaterial', bytes: 48, vars: [{ name: '_BaseColor' }, { name: '_Smoothness' }, { name: '_BumpScale' }] }],
      textures: [{ name: '_BaseMap' }, { name: '_BumpMap' }], disasm: { DXBC: '11.dxbc.txt' } },
    { id: 13, key: '13', stage: 'ps', name: 'Shader 13', entry: 'FragPrefilter', encoding: 'DXBC', flags: [['@cmdline', '/O3']], files: [],
      cbuffers: [{ name: '$Globals', bytes: 32, vars: [{ name: '_BlurTaps' }, { name: '_Threshold' }, { name: '_SourceTex_TexelSize' }] }],
      textures: [{ name: '_SourceTex' }], disasm: { DXBC: '13.dxbc.txt' } },
  ];
  writeCase(dir, { actions, counters, state, shaders, files: { '11.dxbc.txt': DXBC, '13.dxbc.txt': DXBC.replace('42', hash === 'a' ? '42' : '99') } });
}

test('case aggregation, metric resolution and weighted averages', () => {
  const d = tmp();
  frame(d);
  const c = new Case(d);
  assert.equal(c.frameEvents().length, 4);
  assert.ok(Math.abs(c.frameMs() - 3.1) < 1e-9);
  assert.equal(c.resolveMetric('ps'), 'ps');
  assert.equal(c.resolveMetric('l1tex'), 'l1tex__t_sector_hit_rate.avg.pct');
  assert.throws(() => c.resolveMetric('dram'), /not collected/);
  const opaque = c.findNodes('Opaque')[0];
  const ag = c.aggregate(c.workUnder(opaque));
  assert.equal(ag.ps.v, 10000);
  assert.equal(ag.ps.how, 'sum');
  // duration-weighted: (90*0.1 + 80*0.9) / 1.0
  assert.ok(Math.abs(ag['l1tex__t_sector_hit_rate.avg.pct'].v - 81) < 1e-9);
  assert.equal(counterKind('sm__inst_executed.sum', 'Absolute'), 'sum');
  assert.equal(counterKind('foo.max', 'Absolute'), 'max');
});

test('query commands render on a synthetic case', () => {
  const d = tmp();
  frame(d);
  let r = cli(['summary', d]);
  assert.equal(r.code, 0, r.err);
  assert.match(r.out, /3\.100 ms|3\.10 ms/);
  assert.match(r.out, /WITHOUT optimisation \(\/Od\): 1/);
  r = cli(['tree', d, 'Camera', '--metrics', 'ps,l1tex']);
  assert.equal(r.code, 0, r.err);
  assert.match(r.out, /~81/);
  r = cli(['tree', d, 'Opaque', '--metrics', 'L1hit%,@work']);
  assert.equal(r.code, 0, r.err);
  assert.match(r.out, /L1hit%/);
  assert.match(r.out, /draws: 2, p50/);
  r = cli(['event', d, '5']);
  assert.match(r.out, /draws\/dispatches inside: 6/);
  r = cli(['top', d, '--in', 'Opaque', '-n', '1']);
  assert.match(r.out, /^\s*4\s/m);
  r = cli(['event', d, '6']);
  assert.match(r.out, /ps invocations \/ viewport pixels = 1\.00/);
  r = cli(['shaders', d]);
  assert.match(r.out, /42 instr, 2 tex, 1 loop, 7 temps/);
  assert.match(r.out, /yes|no/);
  r = cli(['shader', d, '11']);
  assert.match(r.out, /optimisation DISABLED/);
  r = cli(['find', d, 'blurtaps']);
  assert.match(r.out, /_BlurTaps/);
  r = cli(['metrics', d, 'l1tex']);
  assert.match(r.out, /weighted avg/);
  r = cli(['event', d, '999']);
  assert.match(r.out, /not an action/);
});

test('compare explains work vs cost and flags changed shader code', () => {
  const a = tmp(); const b = tmp();
  frame(a);
  frame(b, { psScale: 4, hash: 'b' });
  const r = cli(['compare', a, b]);
  assert.equal(r.code, 0, r.err);
  assert.match(r.out, /Bloom/);
  assert.match(r.out, /ps \+300%/);
  assert.match(r.out, /CHANGED/);
  const r2 = cli(['compare', a, b, 'Bloom']);
  assert.match(r2.out, /REGION/);
});

test('shaderStats parses DXBC disassembly', () => {
  const d = tmp();
  frame(d);
  const c = new Case(d);
  const st = shaderStats(c, c.shaderById.get(11));
  assert.equal(st.instrSlots, 42);
  assert.equal(st.temps, 7);
  assert.equal(st.samples, 2);
  assert.equal(st.loops, 1);
});

test('counter presets expand to patterns and names', () => {
  const e = expandCounterSpec('generic,nv-memory,sm__inst_executed.sum,re:^foo');
  assert.deepEqual(e.families, ['generic']);
  assert.ok(e.patterns.some((p) => p.includes('dram__bytes_op')));
  assert.ok(e.patterns.includes('^foo'));
  assert.deepEqual(e.names, ['sm__inst_executed.sum']);
});

test('find-source ranks the right project file', { skip: !fs.existsSync(PROJECT) }, () => {
  const d = tmp();
  frame(d);
  let r = cli(['find-source', d, '11', '--project', PROJECT]);
  assert.equal(r.code, 0, r.err);
  const first = r.out.split('\n').find((l) => /^\s*\d+\.\d/.test(l));
  assert.match(first, /HeroLit\.shader/);
  r = cli(['find-source', d, '13', '--project', PROJECT]);
  assert.match(r.out.split('\n').find((l) => /^\s*\d+\.\d/.test(l)), /Bloom\.shader/);
  assert.doesNotMatch(r.out, /should_be_skipped/);
});

function makeZip(entries) {
  const locals = []; const cds = []; let off = 0;
  for (const [name, data] of entries) {
    const comp = zlib.deflateRawSync(data);
    const n = Buffer.from(name);
    const lh = Buffer.alloc(30); lh.writeUInt32LE(0x04034b50, 0); lh.writeUInt16LE(20, 4); lh.writeUInt16LE(8, 8);
    lh.writeUInt32LE(comp.length, 18); lh.writeUInt32LE(data.length, 22); lh.writeUInt16LE(n.length, 26);
    const cd = Buffer.alloc(46); cd.writeUInt32LE(0x02014b50, 0); cd.writeUInt16LE(20, 6); cd.writeUInt16LE(8, 10);
    cd.writeUInt32LE(comp.length, 20); cd.writeUInt32LE(data.length, 24); cd.writeUInt16LE(n.length, 28); cd.writeUInt32LE(off, 42);
    locals.push(lh, n, comp); cds.push(cd, n);
    off += 30 + n.length + comp.length;
  }
  const cdBuf = Buffer.concat(cds);
  const end = Buffer.alloc(22); end.writeUInt32LE(0x06054b50, 0); end.writeUInt16LE(entries.length, 8); end.writeUInt16LE(entries.length, 10);
  end.writeUInt32LE(cdBuf.length, 12); end.writeUInt32LE(off, 16);
  return Buffer.concat([...locals, cdBuf, end]);
}

test('setup-nvperf extracts the host library from an SDK zip', () => {
  const home = tmp();
  const zip = path.join(home, 'NVIDIA_Nsight_Perf_SDK_2025.5_Windows.zip');
  const dllName = process.platform === 'win32' ? 'nvperf_grfx_host.dll' : 'libnvperf_grfx_host.so';
  fs.writeFileSync(zip, makeZip([
    [`NvPerf/bin/x64/${dllName}`, Buffer.from('REAL')],
    [`NvPerf/samples/D3D12/bin/x64/Release/${dllName}`, Buffer.from('SAMPLE')],
    ['NvPerf/include/nvperf_host.h', Buffer.from('//')],
  ]));
  const prev = { HOME: process.env.HOME, APPDATA: process.env.APPDATA };
  process.env.HOME = home; process.env.APPDATA = path.join(home, 'AppData');
  try {
    const r = setupNvPerf({ from: zip });
    assert.ok(r.ok, r.text);
    const dest = process.platform === 'win32' ? path.join(home, 'AppData', 'renderdoc', 'plugins', 'nv', dllName) : path.join(home, '.renderdoc', 'plugins', 'nv', dllName);
    assert.equal(fs.readFileSync(dest, 'utf8'), 'REAL');
    const miss = setupNvPerf({ from: path.join(home, 'nope.zip') });
    assert.equal(miss.ok, false);
    assert.match(miss.text, /ASK THE USER/);
  } finally {
    process.env.HOME = prev.HOME; process.env.APPDATA = prev.APPDATA;
  }
});

test('rdjob.py is Python 3.6 compatible and expands includes like qrenderdoc', { skip: spawnSync('python3', ['--version']).status !== 0 }, () => {
  const job = path.join(SKILL, 'scripts', 'rdjob.py');
  const code = `
import importlib.util, os
os.environ["RDGPU_IMPORT_ONLY"] = "1"
spec = importlib.util.spec_from_file_location("rdjob", ${JSON.stringify(job)})
m = importlib.util.module_from_spec(spec); spec.loader.exec_module(m)
files = {"main.hlsl": '#include "lib/common.hlsl"\\nfloat4 main() : SV_Target { return F(); }', "lib/common.hlsl": "#pragma once\\nfloat4 F() { return 1; }"}
out = m.expand_includes(files["main.hlsl"], files)
assert "float4 F()" in out and "#include" not in out and "// #pragma once" in out, out
assert m.safe_rel("C:\\\\Users\\\\x\\\\Temp\\\\..\\\\a.hlsl") == "Users/x/Temp/a.hlsl"
print("ok")`;
  const r = spawnSync('python3', ['-c', code], { encoding: 'utf8' });
  assert.equal(r.status, 0, r.stderr);
  const v = spawnSync('vermin', ['-q', '--no-tips', '--violations', '-t=3.6-', job], { encoding: 'utf8' });
  if (v.status !== null && !v.error) assert.equal(v.stdout.trim(), '', `vermin: ${v.stdout}`);
});

// ---------------------------------------------------------------- live (optional)

const LIVE = process.env.RDGPU_TEST_CAPTURE;
test('live: open + draw + experiment on a real capture', { skip: !LIVE, timeout: 900000 }, () => {
  const work = tmp();
  const cap = path.join(work, path.basename(LIVE));
  fs.copyFileSync(LIVE, cap);
  let r = cli(['open', cap], { timeout: 600000 });
  assert.equal(r.code, 0, r.err);
  assert.match(r.out, /PASSES/);
  const eid = Number((r.out.match(/TOP EVENTS\n.*\n\s*(\d+)\s/) || [])[1]);
  assert.ok(eid > 0);
  r = cli(['draw', cap, String(eid)], { timeout: 300000 });
  assert.equal(r.code, 0, r.err);
  r = cli(['source', cap, String(eid)], { timeout: 300000 });
  assert.equal(r.code, 0, r.err);
  r = cli(['experiment', cap, String(eid), '--repeat', '2'], { timeout: 600000 });
  assert.equal(r.code, 0, r.err);
  assert.match(r.out, /original/);
  r = cli(['session', cap, '--idle', '60'], { timeout: 300000 });
  assert.equal(r.code, 0, r.err);
  assert.match(r.out, /session (ready|open|already open)/);
  r = cli(['draw', cap, String(eid)], { timeout: 300000 });
  assert.equal(r.code, 0, r.err);
  assert.match(r.err, /in the open session|in rdc session/);
  r = cli(['session', cap, '--stop']);
  assert.match(r.out, /session (stop|.*closed)/);
});
